### ISSUE TITLE
Initial Setup

### ISSUE THREAD

**Issue by 256dpi** [mqttjs/mqtt-server#1]
@mcollina Can you setup the travis stuff? And is it okay if push the package under my account to npm?

**Comment by mcollina** [comment]
Just add myself as owner too :).

**Comment by mcollina** [comment]
Setted the repo team to be 'owner', so you can do these things yourself.

**Comment by 256dpi** [comment]
Ok, didn't know that npm supports that. It looks like that a non-admin of the organization can't do that.

**Comment by mcollina** [comment]
well, I added travis, so you should be ok :D.
